###
GET http://localhost:3000/
###

GET http://localhost:3000/user

###

GET http://localhost:3000/user?name=Ortal%20Golzar

###

GET http://localhost:3000/user?_id=6597e7cacefcbcebf5ffc50b

###

GET http://localhost:3000/user/206777900


###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "ortal gol",
    "_id": "1233456"
    
}

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "post_id": "123",
    "user_name": "1233456",
    "content": "hello"
    
}
###

###
GET http://localhost:3000/comments
###

###

GET http://localhost:3000/user?_id=1233456

###

DELETE http://localhost:3000/user/12334561

###

GET http://localhost:3000/user/206777900

###

GET http://localhost:3000/user/1233456


###

PUT http://localhost:3000/user/1233456

Content-Type: application/json
{
    "name": "nameeee",
    "_id": "1233456"
    
}
###
DELETE http://localhost:3000/comments/65995d035a4519ecacf6bc78

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ortal@gmail.com",
    "password": "1233456"
}