###
GET http://localhost:3000/
###

GET http://localhost:3000/user

###

//GET http://localhost:3000/auth/user?name=Ortal%20Golzar

###

GET http://localhost:3000/user?_id=6597e7cacefcbcebf5ffc50b

###

GET http://localhost:3000/user/206777900


###

//POST http://localhost:3000/auth/user
//Content-Type: application/json

//{
    //"email": "lala@gmail.com",
   // "password": "123456"
   // "name": "ortal gol",
   // "_id": "1233456"
    
//}

###
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: JWT c55ec6032cf6be3235534ece630f2e0b856be45923fabe613979b186f359a8448306cda3d01c14710a91ac3ee7e15126cc061be82c74cf935645fe91a9c63d47

{
    "post_id": "11223",
    "user_name": "1233456",
    "content": "hello"
    
}
###

###
GET http://localhost:3000/comments
Authorization: JWT c55ec6032cf6be3235534ece630f2e0b856be45923fabe613979b186f359a8448306cda3d01c14710a91ac3ee7e15126cc061be82c74cf935645fe91a9c63d47
###

###

GET http://localhost:3000/user?_id=1233456

###

DELETE http://localhost:3000/user/12334561

###

GET http://localhost:3000/user/206777900

###

GET http://localhost:3000/user/1233456


###

PUT http://localhost:3000/user/1233456

Content-Type: application/json
{
    "name": "nameeee",
    "_id": "1233456"
    
}
###
DELETE http://localhost:3000/comments/65995d035a4519ecacf6bc78

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ortal1@gmail.com",
    "password": "1233456"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ortal1@gmail.com",
    "password": "1233456"
}